### ISSUE TITLE
Reload chunks on dig

### ISSUE THREAD

**Issue by lukesmith02** [phase/PhaseBot#16]
```
$ getblock 1 0 0
Gravel
$ dig 1 0 0
Digging at: 0 64 245
Block wait time: 3000.0
 done
Done digging at: 0 64 245
$ getblock 1 0 0
Gravel
$ getblock 1 1 0
Air
$ dig 1 0 0
Digging at: 0 64 245
Block wait time: 3000.0
 done
Done digging at: 0 64 245
$ dig 1 0 0
Digging at: 0 64 245
Block wait time: 3000.0
 done
Done digging at: 0 64 245
$ getblock 1 0 0
Gravel
$ getblock 1 1 0
Air
```

Simply test here showing that the program doesn't update chunks after digging.

**Comment by phase** [comment]
Well that doesn't make sense... Scripts like BusyBeaver and Langton's Ant work fine... Are you sure the blocks are actually being broken server-side? 

@VoltzLive did you get this error?

**Comment by lukesmith02** [comment]
if i place gravel infront of me, log out, run phasebot, ask it whats infront of me (getblock 1 0 0), it will tell me gravel. then if i tell it to digblock 1 0 0, then ask again, it says there's still gravel. If i then close out of the bot and log on, the gravel has been dug.

**Comment by lukesmith02** [comment]
Maybe I am running the program wrong.

**Comment by phase** [comment]
Check that commit. You have to run `getblock` again after you've broken it.
