### ISSUE TITLE
Bot get position Y and stop fly

### ISSUE THREAD

**Issue by MALW3R3** [phase/PhaseBot#24]
Hello my bot only move on X and Z coordinates but he FLY ! and he got kick for fly how can i say him to get block on ground and start move from that block

**Comment by MALW3R3** [comment]
@phase

**Comment by speedAccount2** [comment]
podasz skype? mam sprawe

**Comment by phase** [comment]
You have to implement your own gravity. My bot does not do that because I didn't want to deal with it.
Putting yours in creative mode will stop this error.
